### PR TITLE
Add Theia Integration package and integration example based on GLSP

### PR DESCRIPTION
**Pull request by martin-fleck-at**
- Extend app for easier integration -- Add listener for state (data, dirty state)
-- Provide app that uses listener for auto-save

- Add Theia integration package -- Wrap React App into Theia widget
-- Adapt style to better fit Theia native look and feel -- Provide client for websocket, mock data (default) and Theia channels -- Provide channel backend for mock data and socket forwarding

- Add example integration based on GLSP workflow -- Add script to download GLSP workflow example server if not present

### CODE REVIEW

**Comment by martin-fleck-at** [comment]
@ivy-lli Hi Lukas, the CI seems to be failing with the following error message:

```
[...]
error /home/ubuntu/workspace/en-inscription_integration-theia/client/node_modules/@theia/electron/node_modules/native-keymap: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/ubuntu/workspace/en-inscription_integration-theia/client/node_modules/@theia/electron/node_modules/native-keymap
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@9.3.0
gyp info using node@16.15.1 | linux | x64
gyp info find Python using Python version 3.9.2 found at "/usr/bin/python3"
gyp info spawn /usr/bin/python3
gyp info spawn args [
gyp info spawn args   '/home/ubuntu/workspace/en-inscription_integration-theia/client/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/workspace/en-inscription_integration-theia/client/node_modules/@theia/electron/node_modules/native-keymap/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/ubuntu/workspace/en-inscription_integration-theia/client/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/node/.cache/node-gyp/16.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/node/.cache/node-gyp/16.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/home/ubuntu/workspace/en-inscription_integration-theia/client/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/node/.cache/node-gyp/16.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/ubuntu/workspace/en-inscription_integration-theia/client/node_modules/@theia/electron/node_modules/native-keymap',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.'
gyp info spawn args ]
Package xkbfile was not found in the pkg-config search path.
[...]
```

I believe we need to install the necessary libraries for the Theia Integration. We already do something similar in our base GLSP image: https://github.com/eclipse-glsp/glsp/blob/master/docker/ci/alpine/Dockerfile. I tried to update the 'Jenkinsfile' accordingly but the CI still keeps failing. Unfortunately, I cannot access the actual Jenkins instance so I don't know if the updated file is actually used or not.

**Comment by ivy-lli** [comment]
Thanks @martin-fleck-at 
I'm not sure if I have the time to review this PR today, if not then I will do that in the new year 🙂🎆

**Comment by martin-fleck-at** [comment]
> Thanks @martin-fleck-at I'm not sure if I have the time to review this PR today, if not then I will do that in the new year slightly_smiling_facefireworks

No problem and I hope you had a great start into the New Year! :fireworks: The PR has a few conflicts now but there was still the underlying issue of the build failing (see comment above). I see that we now have a few conflicts, should I resolve them first or will you have a look at them together with the failing build?

**Comment by ivy-lli** [comment]
Hi @martin-fleck-at 

We work currently integrating the current standalone into our Designer (Eclipse) product. In addition, we still refactoring a lot of code in the server part, so there will also be some changes in the client. 
Until this work is not done, I think it makes no sense to merge this PR. 

I think we will review this later on (in 1 or 2 weeks) and maybe rebuild your work on top of the latest inscription editor code and with the process editor. 

If you're curious about how to proceed with the vscode integration, I think you can use the state of the master branch where also this branch is based on.

**Comment by martin-fleck-at** [comment]
@ivy-lli Thank you for letting me know! Then I'll start with the VS Code integration based on the same branch as the Theia integration and leave this integration for now. If you want to pick it up again or need anything else, just let me know.

**Comment by ivy-lli** [comment]
> @ivy-lli Thank you for letting me know! Then I'll start with the VS Code integration based on the same branch as the Theia integration and leave this integration for now. If you want to pick it up again or need anything else, just let me know.

Perfect. Sorry for the delay!

**Comment by ivy-lli** [comment]
Thanks @martin-fleck-at 
As this is integrated now in our theia-integration repo, I will close this PR and at least stale the branch.

**Pull request closed without merging**
