### PR TITLE
agile-uni: introduce start request 'request' part

### PR DESCRIPTION
**Pull request by ivy-rew**

### CODE REVIEW

**Comment by ivy-rew** [comment]
I'm too stupid to fill the mask with real data from the inscription backend: any idea what I'm missing?
request-noData

**Review by ivy-lli — APPROVED** [review]
Cool stuff :partying_face:

**Comment by alexsuter** [comment]
Failing build since june 21. can I close this PR and stale this branch?

**Comment by ivy-lli** [comment]
-> Stale branch

**Comment by alexsuter** [comment]
thanks for reducing cpu cycles and saving the ENV :seedling:

**Pull request closed without merging**
